general {
    lock_cmd = pidof hyprlock || hyprlock
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

# 1. Dim screen after 2.5 min of inactivity
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Lock screen after 5 min of inactivity
listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

# 3. Turn off screen after 5.5 min of inactivity
listener {
    timeout = 330
    on-timeout = hyprctl dispatch "hl.dsp.dpms({ state = 'off' })"
    on-resume = hyprctl dispatch "hl.dsp.dpms({ state = 'on' })"
}

# 4. Suspend system after 30 min of inactivity
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
