general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key to turn on the display.
    ignore_dbus_inhibit = false             # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false          # whether to ignore systemd-inhibit --what=idle inhibitors
}

# Dims the display
listener {
    timeout = 60
    on-timeout = { brightnessctl -s && brightnessctl s 1% ;}
    on-resume = brightnessctl -r
}

# Lock it first before dpms off so that screen won't show for a moment after wake up.
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

# DPMS off
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off #do not turn off display while media is playing
    on-resume = hyprctl dispatch dpms on
}

# Suspend
listener {
    timeout = 500
   on-timeout = systemctl suspend
}

