#!/usr/bin/env bash
WAL_CACHE="$HOME/.cache/wal/colors"
HYPR_WAL="$HOME/.cache/hypr/colors.conf"

mkdir -p "$(dirname "$HYPR_WAL")"

{
    echo "# Generated by pywal"
    echo "general {"
    echo "    col.active_border = 0xFF$(sed -n '7p' "$WAL_CACHE" | tail -c 7)"
    echo "}"
    echo "decoration {"
    echo "	  shadow {"
    echo "		  color = 0x55$(sed -n '6p' "$WAL_CACHE" | tail -c 7)"
    echo "	  }"
    echo "}"
} > "$HYPR_WAL"
